package src.core;

public enum TileType {
	// path tile types
	PATH,
	PATH_VERTICAL,
	PATH_HORIZONTAL,
	PATH_TURN_UP_RIGHT,
	PATH_TURN_UP_LEFT,
	PATH_TURN_DOWN_RIGHT,
	PATH_TURN_DOWN_LEFT,
	PATH_TURN_LEFT_UP,
	PATH_TURN_LEFT_DOWN,
	PATH_TURN_RIGHT_UP,
	PATH_TURN_RIGHT_DOWN,

	GRASS,
	ROCK,
	WATER
}
